#!/usr/bin/env bash

# prototype for artifact
# building side

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'


clean() {
    if [ -d "$build" ]; then
	if rm -rf "$build"; then
	    echo "[remove] $build"
	    exit 0
	fi
    else
	echo "[skip] $build already removed"
	exit 0
    fi
}

build() {
    local input="$1"

    declare -n ref="$input"

    case "$input" in
	assets)
	    ref_src="${ref[src]}"
	    ref_out="${ref[out]}"

	    if [[ ! -d "$ref_out" ]]; then
		mkdir -p -- "$ref_out"
	    else
		echo "[copy] $ref_out"
		cp -ruT "$ref_src" "$ref_out"
	    fi
	    ;;
	*)
	    echo "what to build?"
	    ;;
    esac
}


tree() {
    local node="$1"

    declare -n ref="$node"

    local arr_len="${#ref[@]}"
    local arr_val="${ref[@]}"

    if is_array "$node"; then
	printf "\n# %s\n" "$node (arr)"

	if (( "arr_len" )); then
	    printf "  + child: (%s)\n" "$arr_val"

	    for i in "${!ref[@]}"; do
		tree "${ref[i]}"
	    done
	fi

    elif is_assoc "$node"; then
	assoc_key="${!ref[@]}"
	assoc_val="${ref[@]}"
	printf "    - %s\n" "$node (assoc)"
	printf '      [%s]\n' "$assoc_key"
    fi
}


is_assoc() {
    local decl
    
    decl=$(declare -p "$1" 2>/dev/null) || return 1

    [[ "$decl" == "declare -A"* ]]
}


is_array() {
    local decl
    
    decl=$(declare -p "$1" 2>/dev/null) || return 1

    [[ "$decl" == "declare -a"* ]]
}


log() {
    if (( VERBOSE )); then
	echo -e "$1"
    fi
}


is_container() {
    is_array "$1"
}


walk() {
    local node="$1"
    local callback="$2"
    shift 2

    if is_container "$node"; then
	declare -n ref="$node"

	for child in "${ref[@]}"; do
	    walk "$child" "$callback" "$@"
	done
    else
	"$callback" "$node" "$@"
    fi
}


count_node() {
    local node="$1"
    local -n assoc="$node"
    local -n count="$2"

    [[ "${assoc[out]}" ]] && count=$((count + 1))
}


count() {
    local input="$1"
    local -i result=0

    walk "$input" count_node result

    echo "$result"
}


stats() {
    local input="$1"
    local -i count=0

    walk "$input" check_node count

    printf '\nGenerated: %d\n' "$count"
}


generate() {
    local input="$1"

    declare -A stats=(
	[success]=0
	[failed]=0
    )

    walk "$input" generate_node stats

    printf '\nGenerated: %d\n' "${stats[success]}"
    printf 'Failed: %d\n' "${stats[failed]}"
}


generate_node() {
    local node="$1"
    local dir
    declare -n page="$node"

    dir=$(dirname -- "${page[out]}")

    if [[ ! -d "$dir" ]]; then
	echo "[create] $dir"
	mkdir -p -- "$dir"

    fi

    local cmd=(
	pandoc
	"${page[src]}"
	-o "${page[out]}"
    )

    if [[ ${page[standalone]:-} == true ]]; then
	cmd+=(--standalone)
    fi

    [[ ${page[templ]+_} ]] && cmd+=(--template="${page[templ]}")

    if [[ ${page[filters]+_} ]]; then
	declare -n filters="${page[filters]}"

	for filter in "${filters[@]}"; do
	    cmd+=(--lua-filter="$filter")
	done
    fi

    if "${cmd[@]}"; then
	printf '[ok] %s\n' "${page[out]}"
	stats[success]=$((stats[success] + 1))
    else
	printf '[err] %s -> %s\n' "$node" "${page[out]}"
	stats[failed]=$((stats[failed] + 1))
    fi
}


## config 

export PANDOC_DATA_DIR="templates"

build="build"

base_filters=(
    "lib/filter/unwrapper.lua"
)

page_filters=(
    "lib/filter/unwrapper.lua"
    "lib/filter/element.lua"
)

declare -A assets=(
    [src]="assets/"
    [out]="build/static/"
)

declare -A header_root=(
    [src]="content/partials/header.md"
    [out]="templates/partials/gen-header.html"
    [templ]="templates/header.html"
    [filters]="base_filters"
)

declare -A header_writings=(
    [src]="content/partials/header-writings.md"
    [out]="templates/partials/gen-header-writings.html"
    [templ]="templates/header.html"
    [filters]="base_filters"
)

declare -A index_root=(
    [src]="content/pages/index.md"
    [out]="build/index.html"
    [templ]="templates/base.html"
    [filters]="page_filters"
    [standalone]=true
)

declare -A index_writings=(
    [src]="content/pages/writings.md"
    [out]="build/writings/index.html"
    [templ]="templates/writings.html"
    [filters]="page_filters"
)

partials=(
    header_root
    header_writings
)

pages=(
    index_root
    index_writings
)

all=(
    partials
    pages
)


## begin

VERBOSE=0
ARG=""

while [[ $# -gt 0 ]]; do
    case "$1" in
	--verbose|-v)
	    VERBOSE=1
	    ;;
	clean)
	    clean
	    ;;
	*)
	    echo -e "${RED}[abort]${NC} command not found"
	    # usage
	    
	    exit 0
	    ;;
    esac

    shift
done

if (( VERBOSE )); then
    set -xe
else
    set -Eeuo pipefail
fi

build assets

generate all
