#!/usr/bin/env bash

# prototype for artifact
# building side

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

build_clean() {
    if [ -d "$BUILD" ]; then
	if rm -rf "$BUILD"; then
	    echo "[remove] '$BUILD' dir"
	    exit 0
	else
	    exit "[error] cannot remove '$BUILD' dir ..."
	    exit 1
	fi
    else
	echo "[skip] '$BUILD' dir was already removed"
	exit 0
    fi
}


discover_files() {
    ROOT="${1:-content}"

    if [[ ! -d "$ROOT"  ]]; then
	echo "error: directory not found: $ROOT" >&2
	exit 1
    fi

    find "$ROOT" -type f -name '*.md' -print
}


build_assets() {
    echo "[copy] '$ASSETS' to '$ASSETS_OUT'"
    echo
    
    if [ -d "$ASSETS" ]; then
	mkdir -p "$ASSETS_OUT"
	cp -ruT "$ASSETS" "$ASSETS_OUT"
    fi
}


is_assoc() {
    local decl
    
    decl=$(declare -p "$1" 2>/dev/null) || return 1

    [[ "$decl" == "declare -A"* ]]
}


is_array() {
    local decl
    
    decl=$(declare -p "$1" 2>/dev/null) || return 1

    [[ "$decl" == "declare -a"* ]]
}


generate() {
    local input="$1"
    shift

    if [ ! -d "$BUILD" ]; then
	echo "[warning] '$BUILD' directory is not found"
	echo "[create] $BUILD"
	echo
	
	mkdir -p "$BUILD"
    fi

    if is_assoc "$input"; then
	declare -n page="$input"

	echo "[generate] $input"

	local cmd=(
	    pandoc
	    "${page[src]}"
	    -o "${page[out]}"
	)

	if [[ ${page[standalone]:-} == true ]]; then
	    cmd+=(--standalone)
	fi

	[[ ${page[templ]+_} ]] && cmd+=(--template="${page[templ]}")


	if [[ ${page[filters]+_} ]]; then
	    declare -n filters="${page[filters]}"
	    
	    for filter in "${filters[@]}"; do
		cmd+=(--lua-filter="$filter")
	    done
	fi

	local dir=$(dirname ${page[out]})

	if [[ ! -d "$dir" ]]; then
	    echo -e "${YELLOW}[warning]${NC} $dir directory is not found"
	    echo "[create] $dir"
	    echo
	    
	    # mkdir -p "$dir"
	fi
	
	# "${cmd[@]}"

	echo "+ ${page[out]}"
	echo
	
    elif is_array "$input"; then
	declare -n items="$input"
	
	for item in "${items[@]}"; do
	    generate "$item"
	done

    else
	pandoc "$input" "$@"

	echo "[artifact] generate $input"
    fi

}


## config 

export PANDOC_DATA_DIR="templates"

BUILD="build"
ASSETS="assets"
ASSETS_OUT="build/assets/static"

base_filters=(
    "lib/filter/unwrapper.lua"
)
page_filters=(
    "lib/filter/unwrapper.lua"
    "lib/filter/element.lua"
)

declare -A header_root=(
    [src]="content/partials/header.md"
    [out]="templates/partials/gen-header.html"
    [templ]="templates/header.html"
    [filters]="base_filters"
)

declare -A header_writings=(
    [src]="content/partials/header-writings.md"
    [out]="templates/partials/gen-header-writings.html"
    [templ]="templates/header.html"
    [filters]="base_filters"
)

declare -A index_root=(
    [src]="content/pages/index.md"
    [out]="build/index.html"
    [templ]="templates/base.html"
    [filters]="page_filters"
    [standalone]=true
)

declare -A index_writings=(
    [src]="content/pages/writings.md"
    [out]="build/writings/index.html"
    [templ]="templates/writings.html"
    [filters]="page_filters"
)

partials=(
    header_root
    header_writings
)

pages=(
    index_root
    index_writings
)

all=(
    partials
    pages
)

## begin

VERBOSE=0
ARG=""

while [[ $# -gt 0 ]]; do
    case "$1" in
	--verbose|-v)
	    VERBOSE=1
	    ;;
	clean)
	    build_clean
	    ;;
	*)
	    echo -e "${RED}[abort]${NC} command not found"
	    # usage
	    
	    exit 0
	    ;;
    esac

    shift
done

if (( VERBOSE )); then
    set -xe
else
    set -Eeuo pipefail
fi


# build_assets

# generate partials

# generate pages

# generate all

find_assoc() {
    
}

count_pages() {
    local input="$1"
    declare -i count=0

    if [ ! -v "$input" ] && ! is_assoc "$input"; then
	echo "Err: $input: No such variable or array"

    elif ! is_assoc "$input"; then
	echo "$input is not Assoc"

	declare -n input="$1"

	for i in "${input[@]}"; do
	    if ! is_assoc "$i"; then
		echo "  $i is not Assoc"
		count_pages "$i"
	    else
		echo "  $i is Assoc"
		declare -n j="$i"
		[[ "${j[out]}" ]] && count=$((count + 1))
	    fi
	done
    else
	echo "$input is Assoc"

	declare -n input="$input"

	[[ "${input[out]}" ]] && count=$((count + 1))
    fi

    echo
    echo "Output: $count"
}

count_pages all

