#!/bin/env bash


VERBOSE=0
DRY_RUN=0

while [[ $# -gt 2 ]]; do
    case "$1" in
	--verbose|-v)
	    VERBOSE=1
	    ;;
	--dry-run|-n)
	    DRY_RUN=1
	    ;;
    esac

    shift
done

TARGET="$1"
OUTPUT="$2"



is_assoc() {
    local decl
    
    decl=$(declare -p "$1" 2>/dev/null) || return 1

    [[ "$decl" == "declare -A"* ]]
}


is_array() {
    local decl
    
    decl=$(declare -p "$1" 2>/dev/null) || return 1

    [[ "$decl" == "declare -a"* ]]
}


find_fonts() {
    local root="$1"
    fonts=()

    if [[ ! -e "$root" ]]; then
	echo "error: $root: No such file or directory"
	return
    fi
    
    local cmd=(
	find
	"$root"
	-type f
	-regextype posix-extended
	-iregex '.*\.(woff2|woff|otf"ttf")$'
	-print0
    )

    mapfile -d '' fonts < <("${cmd[@]}")

    if [[ "${#fonts[@]}" -lt 1 ]]; then
	log_err "could not find any fonts in this directory"
	return
    fi
	   
    return
}

parse_font() {
    local font="$1"

    echo "$font"
}

parse_variant() {
    local variant="$1"

    weight=400
    style=normal
    stretch=normal
    variable=false

    case "$variant" in
	*Italic)
	    style=italic
	    variant=${variant%Italic}
	    ;;
	*Oblique)
	    style=oblique
	    variant=${variant%Oblique}
	    ;;
	*Text)
	    style=text
	    variant=${variant%Text}
    esac

    case "$variant" in
	*Variable*|*\[wght\]*)
	    variable=true
	    variant=$(echo "$variant" | sed 's/\[[^]]*\]//g')
	    ;;
    esac

    case "$variant" in
	*Condensed)
	    stretch=condensed
	    variant=${variant%Condensed}
	    ;;
	*SemiCondensed)
	    stretch=semi-condensed
	    variant=${variant%SemiCondensed}
	    ;;
	*Expanded)
	    stretch=expanded
	    variant=${variant%Expanded}
	    ;;
    esac

    case "${variant,,}" in
	""|regular)
	    weight=400
	    ;;
	thin)
	    weight=100
	    ;;
	ultralight|extralight)
	    weight=200
	    ;;
	light)
	    weight=300
	    ;;
	book)
	    weight=350
	    ;;
	text)
	    weight=450
	    ;;
	medium)
	    weight=500
	    ;;
	semibold|demibold)
	    weight=600
	    ;;
	bold)
	    weight=700
	    ;;
	ultrabold|extrabold)
	    weight=800
	    ;;
	black|heavy)
	    weight=900
	    ;;
    esac

    if $variable; then
	weight="100 900"
    fi
}

info() {
    if (( VERBOSE )); then
	echo "$1" >&2
    fi
}


log_err() {
    local script="${BASH_SOURCE[0]##*/}"
    local line_num="${BASH_LINENO[0]}"
    echo "${script}:${line_num}: $*" >&2
}


if (( DRY_RUN )); then
    exec 3>&1
else
    exec 3>"$OUTPUT"
fi


if [[ ! -e "$TARGET" ]]; then
	echo "Dir not found"
	exit 1
fi

declare -A groups

font_count=0
family_count=0


info ""
info "+ FIND FONTS"

fonts_dir="$TARGET"

if ! find_fonts "$fonts_dir"; then
    echo "could not find any fonts in this directory"
else
    for font in "${fonts[@]}"; do
	parse_font "$font"
    done
fi

# for filename in "$TARGET"/*.{woff,woff2}; do
#     [ -e "$filename" ] || continue

#     path="$filename"
#     filename=$(basename -- "$path")
    
#     base="${filename%.*}"
#     variant="${base##*-}"
#     family="${base%-*}"
#     format="${filename##*.}"

#     if [[ "$family" == "$base" ]]; then
# 	family="$base"
# 	variant="Regular"
#     fi

#     style_source="$variant"

    
#     parse_variant "$variant"


#     case "${format,,}" in
# 	woff2)
# 	    priority=1
# 	    css_format="woff2"
# 	    ;;
# 	woff)
# 	    priority=2
# 	    css_format="woff"
# 	    ;;
# 	ttf)
# 	    priority=3
# 	    css_format="truetype"
# 	    ;;
# 	otf)
# 	    priority=4
# 	    css_format="opentype"
# 	    ;;
#     esac


#     render_priority=0
#     style_priority=0

#     case "$style_source" in
# 	*Regular|*Text|*Book|*Roman)
# 	    render_priority=1
# 	    style_priority=1
# 	    ;;
# 	*Italic)
# 	    render_priority=2
# 	    style_priority=2
# 	    ;;
# 	*)
# 	    render_priority=3;
# 	    style_priority=3
# 	    ;;
#     esac

      
#     key="${render_priority}|${family}|${weight}|${style}|${stretch}"

#     src="url('/static/fonts/$filename') format('$css_format')"
#     record="${priority}|${style_priority}|${src}|${filename}"

#     groups["$key"]+="$record"$'\n'

#     ((font_count++))

#     log "| + FONT"
#     log "| | - file: ($filename)"
#     log "| | - family: ($family)"
#     log "| | - style: ($style) weight: ($weight) stretch: ($stretch) variable: ($variable)"
#     log "| | - css_format: ($css_format) format_priority: ($priority)"
#     log "| | - style_source: ($style_source)"
#     log "| | - render_priority: ($render_priority) style_priority: ($style_priority)"
# done


# family_count=$(printf "%s\n" "${!groups[@]}" | cut -d'|' -f2 | sort -u | wc -l)
# group_keys=$(printf "%s\n" "${!groups[@]}" | cut -d'|' -f2 | sort -u)


# log "+ COUNT"
# log "| + family count ($family_count):"

# while IFS= read -r family; do
#     count_faces=$(printf "%s\n" "${!groups[@]}" | grep "${family}|" | wc -l)

#     log "| | - $family ($count_faces faces)"
# done < <(printf "%s\n" "${!groups[@]}" | cut -d'|' -f2 | sort -u)


# log "+ GENERATE"
# keys=$(printf "%s\n" "${!groups[@]}")

# {
#     echo "/*"
#     echo " * This file was generated by 2fontface."
#     echo " */"
#     echo
# } >&3

# for key in $(printf "%s\n" "${!groups[@]}" | sort -u); do
#     log "| - generating $key"

#     IFS='|' read -r _ family weight style stretch <<< "$key"
    
#     {
# 	echo "@font-face {"
# 	echo "    font-family: '${family}';"
# 	echo "    src:"

# 	mapfile -t lines < <(
# 	    printf "%s" "${groups[$key]}" |
# 		sort -t'|' -k1,1n -k2,2n -k3,3
# 	)

# 	for ((i=0; i<${#lines[@]}; i++)); do
# 	    IFS='|' read -r _ _ src filename <<< "${lines[$i]}"
	    
# 	    if (( i == ${#lines[@]} - 1 )); then
# 		echo "        $src;"
# 	    else
# 		echo "        $src,"
# 	    fi
# 	done

# 	echo "    font-weight: ${weight};"
# 	echo "    font-style: ${style};"

# 	if [[ "$stretch" != "normal" ]]; then
# 	    echo "    font-stretch: ${stretch};"
# 	fi
	
# 	echo "    font-display: swap;"
# 	echo "}"
# 	echo
#     } >&3
# done

# exec 3>&-

# {
#     echo
#     echo "Generated: $OUTPUT"
    
#     echo "Families:  $family_count"
#     for family in $(printf "%s\n" "${!groups[@]}" | cut -d'|' -f 2 | sort -u); do
# 	count=$(printf "%s\n" "${!groups[@]}" | grep "${family}|" | wc -l)
# 	echo "  $family ($count faces)"
#     done

#     echo "Faces:     ${#groups[@]}"
#     echo "Files:     $font_count"
# } >&2

